[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dl-utils"
version = "0.1.0"
requires-python = ">=3.14,<3.15"
dependencies = [
    "einops==0.8.2",
    "imageio==2.37.4",
    "ipython==9.16.0",
    "matplotlib==3.11.1",
    "matplotlib-inline==0.2.2",
    "numpy==2.4.4",
    "pillow==12.2.0",
    "requests==2.34.2",
    "torch==2.13.0",
    "torchvision==0.28.0",
    "tqdm==4.70.0",
]

[project.optional-dependencies]
celeba = [
    "kagglehub==1.0.2",
]
examples = [
    "aiohttp==3.14.3",
    "albumentations==2.0.8",
    "datasets==5.0.1",
    "diffusers==0.39.0",
    "kagglehub==1.0.2",
    "pandas==3.0.5",
]
test = [
    "pytest==9.1.1",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.setuptools.packages.find]
where = ["."]
include = ["dl_utils*"]

[tool.setuptools.package-data]
"dl_utils.data" = ["*.json"]

[dependency-groups]
dev = [
    "pyright==1.1.411",
    "ruff==0.16.4",
]
